import React from 'react'
import Head from "next/head";
import styles from "@/styles/Events.module.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";

const about = () => {
  return (
    <>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
    </>
  )
}

export default about