import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { GiMoebiusTriangle } from "react-icons/gi";
import { CgMouse } from "react-icons/cg";

export default function Home() {

  return (
    <>
      <Head>
        <title>Elite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className={styles.box1}>
        <img src="https://arino-html.vercel.app/assets/img/hero_bg.jpeg" alt="" />
      </div>

      <Navbar />
      <main className={styles.main}>

        <div className={styles.page1}>
          <h2>
            Innovation <br />is <span>Intrinsic</span>
          </h2>
          <div className={styles.follow}>Follow Us - <span className={styles.insta}><Link href='#'>Instagram</Link></span> | <span className={styles.ghub}><Link href='#'>Github</Link></span></div>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '4rem' }}>
            <p style={{ fontSize: '1.2rem', letterSpacing: '0.5px' }}>Get a Quote <span>&#8594;</span></p>
            <p style={{ fontSize: '1.1rem', letterSpacing: '0.5px' }}>We deliver best problem-solving solutions for our clients and provide the finest finishing <br />products in the present and upcoming future.</p>
          </div>
          <CgMouse className={styles.mousebtn} size={32} />
          
        <div className={styles.tri1}><img src="/tri.png" /></div>
        <div className={styles.tri2}><img src="/tri.png" /></div>
        <div className={styles.tri3}><img src="/tri.png" /></div>
        </div>

        <div className={styles.page2}>
          <div className={styles.box2}>
          <img src="" alt="" />
          </div>
        </div>


      </main>
    </>
  );
}
