import { useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import Link from "next/link";
import { CgMouse } from "react-icons/cg";
import { FaGithub } from "react-icons/fa";
import { IoLogoInstagram } from "react-icons/io";
import { FaLinkedinIn } from "react-icons/fa6";
import { Swiper, SwiperSlide } from 'swiper/react';
import { FreeMode, Pagination,EffectCreative  } from 'swiper/modules';
import 'swiper/css';
import "@/styles/Swiper.module.css"
import 'swiper/css/pagination';
import 'swiper/css/free-mode';
import 'swiper/css/effect-creative';
import { FaArrowAltCircleRight } from "react-icons/fa";



export default function Home() {
  const [fixedImgSrc, setFixedImgSrc] = useState("");
  const [showFixedImg, setShowFixedImg] = useState(false);

  const teamMembers = [
    { name: "Melina Opole", role: "Web Developer", imageSrc: "https://arino-html.vercel.app/assets/img/member_4.jpeg" }, { name: "Melina Opole", role: "Web Developer", imageSrc: "https://arino-html.vercel.app/assets/img/member_4.jpeg" }, { name: "Melina Opole", role: "Web Developer", imageSrc: "https://arino-html.vercel.app/assets/img/member_4.jpeg" }, { name: "Melina Opole", role: "Web Developer", imageSrc: "https://arino-html.vercel.app/assets/img/member_4.jpeg" }, { name: "Melina Opole", role: "Web Developer", imageSrc: "https://arino-html.vercel.app/assets/img/member_4.jpeg" }, { name: "Melina Opole", role: "Web Developer", imageSrc: "https://arino-html.vercel.app/assets/img/member_4.jpeg" }
  ];

  const handleMouseEnter = (imgSrc) => {
    setFixedImgSrc(imgSrc);
    setShowFixedImg(true);
  };

  const handleMouseLeave = () => {
    setShowFixedImg(false);
  };

  return (
    <>
      <Head>
        <title>Elite</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className={styles.box1}>
        <img src="https://arino-html.vercel.app/assets/img/hero_bg.jpeg" alt="" />
      </div>

      <Navbar />
      <main className={styles.main}>
        <div
          className={styles.fixedimg}
          style={{
            display: showFixedImg ? "block" : "none",
            backgroundImage: fixedImgSrc ? `url(${fixedImgSrc})` : "none",
          }}
          onMouseEnter={() => setShowFixedImg(true)}
          onMouseLeave={handleMouseLeave}
        ></div>

        <div className={styles.page1}>
          <h2>
            Innovation <br />is <span>Intrinsic</span>
          </h2>
          <div className={styles.follow}>
            Follow Us - <span className={styles.insta}><Link href='#'>Instagram</Link></span> |{" "}
            <span className={styles.ghub}><Link href='#'>Github</Link></span>
          </div>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '4rem' }}>
            <p style={{ fontSize: '1.2rem', letterSpacing: '0.5px' }}>Get a Quote <span>&#8594;</span></p>
            <p style={{ fontSize: '1.1rem', letterSpacing: '0.5px' }}>
              We deliver best problem-solving solutions for our clients and provide the finest finishing <br />
              products in the present and upcoming future.
            </p>
          </div>
          <CgMouse className={styles.mousebtn} size={32} />

          <div className={styles.tri1}><img src="/tri.png" alt="" /></div>
          <div className={styles.tri2}><img src="/tri.png" alt="" /></div>
          <div className={styles.tri3}><img src="/tri.png" alt="" /></div>
        </div>

        <div className={styles.page2}>
          <div className={styles.box2}>
            <div style={{ width: '50%' }}>
              <h2>Did You Know ?</h2>
              <p style={{ width: '70%' }}>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore libero, minima accusamus vel voluptatum,
                quod cum nam impedit eos, doloribus nihil repellendus consectetur.
              </p>
            </div>
            <div style={{ marginTop: '5rem' }}>
              <h3>
                <span className={styles.eight}>8</span>
                <span style={{ fontSize: '5rem', fontWeight: '500', color: 'transparent', WebkitTextStroke: '1px white' }}>
                  +
                </span>{" "}
                <br />
                <span style={{ lineHeight: '1rem' }}>Projects Delivered</span>
              </h3>
            </div>
            <div className={styles.gola}></div>
          </div>

          <div className={styles.services}>
            <div style={{ width: '30%' }} className={styles.services_help}>
              <h1>What We Can Do </h1>
              <h2>Services we can help you with</h2>
              <p>
                Our Services <span>&#8594;</span>
              </p>
            </div>

            <div style={{}} className={styles.services_img}>
              <div className={styles.services_img1}>
                <h1>
                  App <br /> Development
                </h1>
              </div>
              <div className={styles.services_img2}>
                <h1>
                  Web <br /> Development
                </h1>
              </div>
              <div className={styles.services_img3}>
                <h1>Ui/Ux Design</h1>
              </div>
              <div className={styles.services_img4}>
                <h1>Technology</h1>
              </div>
            </div>
          </div>
        </div>

        <div className={styles.page3}>
          <h2>Our Projects</h2>

          <div className={styles.elem_container}>
            <div
              className={styles.elem}
              onMouseEnter={() =>
                handleMouseEnter(
                  "https://blog.depositphotos.com/wp-content/uploads/2021/11/20-Best-Website-Designs-from-Awwwards-in-2021-5.jpg.webp"
                )
              }
              onMouseLeave={handleMouseLeave}
            >
              <div className={styles.overlay}></div>
              <h1 style={{ display: 'flex' }}>PROJECT ONE <span style={{ display: 'flex', margin: 'auto 0', position: 'absolute', right: '4rem', top: '2rem', scale: '0.7' }}> <Link href='/'><FaGithub style={{ marginRight: '2rem' }} /></Link> <Link href='/'><FaArrowAltCircleRight /></Link></span></h1>
            </div>
            <div
              className={styles.elem}
              onMouseEnter={() =>
                handleMouseEnter(
                  "https://blog.depositphotos.com/wp-content/uploads/2021/11/20-Best-Website-Designs-from-Awwwards-in-2021-1.jpg.webp"
                )
              }
              onMouseLeave={handleMouseLeave}
            >
              <div className={styles.overlay}></div>
              <h1 style={{ display: 'flex' }}>PROJECT TWO <span style={{ display: 'flex', margin: 'auto 0', position: 'absolute', right: '4rem', top: '2rem', scale: '0.7' }}> <Link href='/'><FaGithub style={{ marginRight: '2rem' }} /></Link> <Link href='/'><FaArrowAltCircleRight /></Link></span></h1>
            </div>
            <div
              className={styles.elem}
              onMouseEnter={() =>
                handleMouseEnter(
                  "https://www.awwwards.com/awards/gallery/2015/11/be-careful-trends-awwwards-09.png"
                )
              }
              onMouseLeave={handleMouseLeave}
            >
              <div className={styles.overlay}></div>
              <h1 style={{ display: 'flex' }}>PROJECT THREE <span style={{ display: 'flex', margin: 'auto 0', position: 'absolute', right: '4rem', top: '2rem', scale: '0.7' }}> <Link href='/'><FaGithub style={{ marginRight: '2rem' }} /></Link> <Link href='/'><FaArrowAltCircleRight /></Link></span></h1>
            </div>
            <div
              className={styles.elem}
              onMouseEnter={() =>
                handleMouseEnter(
                  "https://assets.awwwards.com/awards/sites_of_the_day/2016/06/awwwards-sotd-Designembraced-1.jpg"
                )
              }
              onMouseLeave={handleMouseLeave}
            >
              <div className={styles.overlay}></div>
              <h1 style={{ display: 'flex' }}>PROJECT FOUR <span style={{ display: 'flex', margin: 'auto 0', position: 'absolute', right: '4rem', top: '2rem', scale: '0.7' }}> <Link href='/'><FaGithub style={{ marginRight: '2rem' }} /></Link> <Link href='/'><FaArrowAltCircleRight /></Link></span></h1>
            </div>
          </div>

          <Link style={{ fontSize: '1rem', display: 'flex', justifyContent: 'flex-end', paddingTop: '2rem', paddingRight: '4rem', fontWeight: 'bold', letterSpacing: '1px' }} href="/"> See All Projects<span style={{ paddingLeft: '0.5rem' }}> &#8594;</span></Link>
        </div>

        <div className={styles.page4}>
          <h2>Our Team</h2>
          <h1>Awesome team <br />members</h1>
          <div style={{ display: 'flex', justifyContent: 'center', marginTop: '4rem', paddingLeft: '1rem', alignItems: 'center' }}>
            <Swiper
              slidesPerView={4}
              spaceBetween={30}
              modules={[Pagination]}
              className="mySwiper"

            >
              {teamMembers.map((member, index) => (
                <SwiperSlide key={index}>
                  <div className={styles.teamcard}>
                    <img src={member.imageSrc} alt={member.name} />
                    <div className="flex flex-col text-white" style={{ position: 'absolute', bottom: '0%', left: '0', padding: '0.5rem' }}>
                      <h3>{member.name}</h3>
                      <p>{member.role}</p>
                    </div>
                    <div className={styles.teamcardicon}>
                      <IoLogoInstagram size={30} style={{ marginBottom: '0.5rem' }} />
                      <FaLinkedinIn size={22} style={{ marginBottom: '0.5rem' }} />
                      <FaGithub size={23} />
                    </div>
                  </div>
                </SwiperSlide>
              ))}
            </Swiper>
          </div>
        </div>

        <div className={styles.page5}>
          <div className={styles.page5gola1}></div>
          <div className={styles.page5gola2}></div>
          <div>
            <h2>Our Blogs</h2>
            <h1>Explore the recent <br />blog</h1>
            <Link href='/'>View More Blog  →</Link>
          </div>

          <img src="/dots.png" alt="" className={styles.dots}/>

          <div style={{ position: 'relative', width: '30vw', height: '30vw', overflow: 'hidden', borderRadius: '10px', backgroundColor: 'black', mixBlendMode: 'difference', transform: 'translateX(-60%)' }}>
          <img src='https://arino-html.vercel.app/assets/img/blog_details_img_1.jpeg' alt='imagenot found' style={{width:'30vw',opacity:'0.8'}}/>
                    <div className="flex flex-col text-white" style={{ position: 'absolute', bottom: '0%', left: '0', padding: '0.5rem' }}>
                      <p style={{fontSize:'0.9rem',color:'#A1A1A1',fontWeight:'500'}}>15 Mar 2024</p>
                      <h3 style={{fontSize:'1.7rem',color:'white',fontWeight:'bold',lineHeight:'2rem'}}>How to become strong during tough days</h3>
                    </div>
          </div>
          

        </div>
        
        <div className={styles.page6}>
        <div className={styles.hbackground}>
      <div className={styles.siteheading}>
        <h2>Inovation is Intrinsic </h2>
        <h2>Inovation is Intrinsic </h2>
        <h2>Inovation is Intrinsic </h2>
      </div>
      </div>
        </div>

      </main>
    </>
  );
}